# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_tets',
                'doc_host': 'https://RainPadjus.github.io',
                'git_url': 'https://github.com/RainPadjus/nbdev_tets',
                'lib_path': 'nbdev_tets'},
  'syms': {'nbdev_tets.core': {'nbdev_tets.core.foo': ('core.html#foo', 'nbdev_tets/core.py')}}}
